### ISSUE TITLE
Step 05 genome table

### ISSUE THREAD

**Issue by TonyMane** [rotheconrad/00_in-situ_GeneCoverage#2]
Greetings, I've been able to use all the scripts for calculating TAD80 from a series of MAGs- super useful!
However, i am having some difficulties with the last script (05_MagicBlast_CoverageMagic_CombineGenomeStats.py). 
I made a small practice directory with n=4 *_genome.tsv files (the TAD80 results for four metagenoems mapped to one MAG).
I then ran the script as such:

```
(base) -bash-4.2$ python ./00_in-situ_GeneCoverage/05_MagicBlast_CoverageMagic_CombineGenomeStats.py -gtd 3248/GD100 -out matrix


Parsing data into summary table ...


Traceback (most recent call last):
  File "./00_in-situ_GeneCoverage/05_MagicBlast_CoverageMagic_CombineGenomeStats.py", line 148, in <module>
    main()
  File "./00_in-situ_GeneCoverage/05_MagicBlast_CoverageMagic_CombineGenomeStats.py", line 144, in main
    args['output_file_prefix']
  File "./00_in-situ_GeneCoverage/05_MagicBlast_CoverageMagic_CombineGenomeStats.py", line 67, in gather_data
    genome = file_basename[1]
IndexError: list index out of range
```
I looked through the dependencies of the '05_MagicBlast_CoverageMagic_CombineGenomeStats.py' script (arparse, oslist.dir, ect), and am fairly confident they are all installed working.

I attach the directory 'GD100' with my n=4 *_genome.tsv files.
[GD100.tar.gz](https://github.com/rotheconrad/00_in-situ_GeneCoverage/files/8718194/GD100.tar.gz)

Any tips/assistance would be welcome.

**Comment by rotheconrad** [comment]
Hey Tony! Thanks. Good to hear.

That last script uses data from the file names and fasta deflines to parse who is who and what's what. The error you received is related to that. I should probably add a note somewhere about expecting naming scheme, or else accept a filename, desired name kind of get up.

The fastest way to resolve this is to have a video meeting and screen share and I can you through a slight modification in the code for your specific naming scheme. Send me an email and we can schedule something.

cheers,
Roth

**Comment by rotheconrad** [comment]
Issue related to file naming scheme. Resolved during video meeting with minor edits to Tony's local copy of the code. File 05_MagicBlast_CoverageMagic_CombineGenomeStats.py lines 64 and 67.
